# Site
name: "The Write Ahead Log"
title: "The Write Ahead Log"
description: "Platform and Product Engineering Journal"
logo: 'assets/images/plf-logo.svg'
favicon: 'assets/images/logo.png'
baseurl: '/blog'
google_analytics: 'G-PWW2W71JX1'
#disqus: 'demowebsite'
mailchimp-list: 'https://platformatory.us17.list-manage.com/subscribe/post?u=8cc2e44e80300ae193f198bcc&amp;id=6246b12a61'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  p6:
    name: pavan
    display_name: Pavan Keshavamurthy
    gravatar: a92e3c1140c93b65879c69ecf47bb1b5
    email: pavan@platformatory.io
    web: https://platformatory.io
    twitter: https://twitter.com/platformatory
    description: "Cofounder at Platformatory. Pavan has handyman experience around systems programming, data, infrastructure and running tech consulting gigs"
  badri:
    name: badri
    display_name: Lakshminarasimhan Parthasarathy    
    avatar: 'assets/images/lakshmi.jpg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: lakshmi@platformatory.io
    web: https://www.platformatory.io
    twitter: https://twitter.com/platformatory
    description: "Principal Engineer at Platformatory; Lakshmi comes with the triad of full stack development, operations and data experience"
  dasa:
    name: dasa
    display_name: Dasa Sathyan
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: srikanth@platformatory.io
    web: https://www.platformatory.io
    twitter: https://twitter.com/platformatory
    description: "Sr Consultant at Platformatory;"
  ashwin:
    name: ashwin
    display_name: Ashwin Venkatesan
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: ashwin@platformatory.io
    web: https://www.platformatory.io
    twitter: https://twitter.com/platformatory
    description: "Platform Engineer at Platformatory specialzing in streaming; Ashwin has previously dabbled in data science, machine learning and predicting box office success for Tollywood movies"
  venkatesh:
    name: venkatesh
    display_name: Venkatesh Keshavamurthy
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: srikanth@platformatory.io
    web: https://www.platformatory.io
    twitter: https://twitter.com/platformatory
    description: "Data Engineer at Platformatory;"
  avinash:
    name: avinash
    display_name: Avinash Upadhyaya
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: avinash@platformatory.io
    web: https://www.platformatory.io
    twitter: https://twitter.com/platformatory
    description: "Platform Engineer at Platformatory specializing in Infrastructure; Avinash is an avid technical evangelist advocating for open source technologies in the local communities through meetups and conferences. He is a Kong Champion and a Confluent Community Catalyst. Apart from consulting, Avinash is an open source contributor with contributions to various projects in the CNCF ecosystem."
  raghav:
      name: raghav
      display_name: Raghavendran Nehru
      avatar: 'assets/images/avatar.png'
      gravatar: b1cc14991db7a456fcd761680bbc8f81
      email: raghav@platformatory.com
      web: https://www.platformatory.io
      twitter: https://twitter.com/platformatory
      description: "Director & Practitioner, North America;"
  Shivaprakash:
      name: Shivaprakash Akki
      display_name: Shivaprakash Akki
      avatar: 'assets/images/shiva.png'
      gravatar: b1cc14991db7a456fcd761680bbc8f81
      email: akkishiva@platformatory.com
      web: https://www.platformatory.io
      twitter: https://twitter.com/platformatory
      description: "Data Platform Engineer at Platformatory, specializing in Site Reliability Engineering (SRE) and Infrastructure. This role involves building and managing reliable systems to ensure high performance and smooth operations."
  Arun:
      name: Arun B Bhat
      display_name: Arun B Bhat
      avatar: 'assets/images/arun.png'
      gravatar: b1cc14991db7a456fcd761680bbc8f81
      email: arun@platformatory.io
      web: https://www.platformatory.io
      twitter: https://twitter.com/platformatory
      description: "SRE Team Lead at Platformatory"
  Subramanya:
      name: Subramanya Madhyastha
      display_name: Subramanya Madhyastha
      avatar: 'assets/images/subramanya_1.jpg'
      gravatar: b1cc14991db7a456fcd761680bbc8f81
      email: subramanya@platformatory.io
      web: https://www.platformatory.io
      twitter: https://twitter.com/platformatory
      description: "Devops Engineer at Platformatory specializing in Site Reliability Engineeing and Infrastructure."
  Vikhyat:
      name: Vikhyat Shetty
      display_name: Vikhyat Shetty
      avatar: 'assets/images/vikhyat.jpg'
      gravatar: b1cc14991db7a456fcd761680bbc8f81
      email: vikhyat@platformatory.com
      web: https://www.platformatory.io
      twitter: https://twitter.com/platformatory
      description: "DevOps/SRE at Platformatory"
  Zeenia:
    name: Zeenia
    display_name: Zeenia Gupta
    avatar: 'assets/images/girl_avatar.jpg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: zeenia@platformatory.com
    web: https://www.platformatory.io
    twitter: https://twitter.com/platformatory
    description: "DevOps engineer at Platformatory specializing in Site Reliability Engineeing (SRE) and Infrastructure. The role involves managing the infrastructre and make sure the cluster are working fine."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
#adsense: "disabled"
#adsense-data-ad-client: "ca-pub-3412143450191416"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
